### ISSUE TITLE
Deep learning (with MINST digits)?

### ISSUE THREAD

**Issue by parenthetical-e** [COGS108/Tutorials#13]
You don't touch on Dl or differential programming. It's kinda a big gap, given the state of things.

Teaching a basic 'ConvNet' to recognize digits is straightforward. You can demo it in a notebook, like your NLP or classification examples. Here is a working code in PyTorch (which is the most pythonic of the available libs). There is a bit going, for sure, but I think you could simplify it down into a single intro lecture.

https://github.com/pytorch/examples/blob/master/mnist/main.py

I'd be happy to do a draft....

**Comment by TomDonoghue** [comment]
Not entirely sure if you are serious about adding this.... but:

Yeh, covering DL would be cool, but there is already no lack of content to cover in 10 weeks, and also entire classes about DL they can go into after this one (so DL might simply be considered out of scope for this class - and you taught me a lot about tight scoping :)). 

That said, it would be awesome to have an available tutorial for DL, if you are offering to draft it together (even if it was offered as bonus content to the advanced students to motivate them to go into the more advanced ML & DL classes). Ultimately content decisions are pretty much up to @voytek , so we'll see what he thinks :).

**Comment by voytek** [comment]
Yeah, we have whole classes here on DL. It's definitely outside the scope of 108.
